# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: api.gouv.fr
baseurl: ""
url: "https://api.gouv.fr"
description: Fabriquez des services en ligne plus simples
menu_options: [
  {
    id: "access",
    label: "Acc√®s"
  },
  {
    id: "contact",
    label: "Support"
  },
  {
    id: "monitoring",
    label: "Monitoring"
  },
  {
    id: "openapi_definition",
    label: "Documentation technique"
  },
  {
    id: "rate_limiting",
    label: "Limite d'usage"
  },
]


# see https://jekyllrb.com/docs/continuous-integration/
exclude: [vendor, app.json, Gemfile.lock]

collections:
  api:
    output: true
  service:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: api	# targets a collection
    values:
      layout: api
      default_logo: logo-generique-startup-carre.jpg

  -
    scope:
      path: ""	# means "all files"
      type: service	# targets a collection
    values:
      layout: service
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown
