# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-ruby/>.
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/api.gouv.fr

    before_install:
      - npx audit-ci -m

    steps:
      - checkout

      # Note the YAML heredoc '|' for nicer formatting
      - run: |
          npm i

      - restore_cache:
          keys:
            - v1-api.gouv.fr-{{ checksum "package.json" }}

      - save_cache:
          key: v1-api.gouv.fr-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: |
          npm run lint
        # get server up and running in the background
      - run:
          command: npm run start
          background: true

      # wait for the server to start responding. We expect Bad Request 400 once it starts listening.
      # so override the shell and have the last command be the : { null } command to force exit code 0.
      - run:
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=5 --read-timeout=10 --timeout=15 -t 50 http://localhost:3000/sitemap.xml
            :

      - run: |
          npm run check-html
      # - run: |
      #     npm run test
